### ISSUE TITLE
BLN map issue

### ISSUE THREAD

**Issue by Jaidendude** [7Cav/7thCavalry_Training_Missions#10] opened 2020-01-22 21:45 UTC
**Description:**
Prior to the introduction of Cavpack 3.8/Cav Training preset update, All students and instructors slotted in for the SOI BLN class had Map Tools in their inventory.

Following the update, they do not.

**Steps to reproduce:**
1. Start the SOI BLN mission file (SOI_BLN_map_ACRE_V1_8.altis)
2. Slot in as either student or instructor
3. Go to inventory and note neither student nor instructor has Map Tools in their inventory. Further, instructors now have a BLUFOR tracker where previously they had a MicroDAGR. Note, instructors correctly have a Vector 21 Nite in their inventory.

**Expected behavior:**
Students should be equipped with Map Tools. Instructors should be equipped with Map Tools, a MicroDAGR and a Vector 21 Nite

**Where did the issue occur?**
Throughout SOI BLN class

**Additional context:**
Issue noticed following updates to presets and introduction of CavPack 3.8

**Comment by longlostblake** [comment] 2020-04-17 17:06
Duplicate of #23 

Closing as this is outdated.

**Closed as completed by longlostblake** 2020-04-17 17:06 UTC
Labels: Issue Report
